<nav class = "navbar navbar-dark bg-dark">
	<div class = "navbar-brand">
		<h1><img class="img-fluid" src="../logos/logo.png"></h1>
	</div>

	<ul class = "nav">
  		<li class = "nav-item">
    		<a class = "nav-link" href = "../php/admHome.php">Home</a>
  		</li>
  		<li class = "nav-item">
    		<a class = "nav-link" href = "../php/admCadastroPalavras.php">Cadastro de Palavras</a>
  		</li>
  		<li class = "nav-item">
    		<a class = "nav-link" href = "../php/admListaPalavras.php">Lista de Palavras</a>
  		</li>
		<li class = "nav-item">
    		<a class = "nav-link" href = "../php/admListaUsuario.php">Lista de Usuários</a>
  		</li>
  		<li class = "nav-item">
    		<a class = "nav-link disabled" href = "../php/admLogout.php" tabindex = "-1" aria-disabled = "true">Logout</a>
  		</li>
	</ul>
</nav>
