<nav class = "navbar navbar-dark bg-dark">
	<div class = "navbar-brand">
		<h1><img class="img-fluid" src="../logos/logo.png"></h1>
	</div>

	<ul class = "nav">
  		<li class = "nav-item">
    		<a class = "nav-link" href = "../php/userHome.php">Home</a>
  		</li>
  		<li class = "nav-item">
    		<a class = "nav-link" href = "../php/userPerfil.php">Perfil</a>
  		</li>
			<li class = "nav-item">
    		<a class = "nav-link" href = "../php/userRegras.php">Regras</a>
  		</li>
  		<li class = "nav-item">
    		<a class = "nav-link" href = "../php/userJogar.php">Jogar</a>
  		</li>
		<li class = "nav-item">
    		<a class = "nav-link" href = "../php/userQuadroLideres.php">Ranking</a>
  		</li>
  		<li class = "nav-item">
    		<a class = "nav-link disabled" href = "../php/userLogout.php" tabindex = "-1" aria-disabled = "true">Logout</a>
  		</li>
	</ul>
</nav>
